### ISSUE TITLE
Missing helipad - Hamar Sykehus

### ISSUE THREAD

**Issue by chjohans** [f99mlu/norwegian-helipads#1]
The attached picture shows where the helipad for "Hamar sykehus" is located. The screenshot is taken from this website: https://www.norgeibilder.no/ - they have updated aerial photos from 2022 so this is fairly accurate and up to date.

![image](https://github.com/f99mlu/norwegian-helipads/assets/24390228/a8d0f20e-7fbf-49fa-bb8b-353de989f932)

**Comment by f99mlu** [comment]
Great!!! Thank you for reporting this missing helipad! I will include it soon. It may take a bit more than a week since I will be on vacation, so sorry in advance for that. But then!!! It will be great. Thanks!

**UPDATE**: I will do it right now!!

**Comment by f99mlu** [comment]
Cannot find a real ICAO for the pad, so I am setting an imaginary one.

**Coordinate**: 60.79903553948816, 11.071898727536071
**Name**: Hamar helikopterplass, Sykehuset
**City**: Hamar
**Region**: Innlandet
**ICAO**: ENZK

**Comment by f99mlu** [comment]
New version of the add-on has been released. Please try it out :).

https://flightsim.to/file/54947/norwegian-helipads
